# Generated by Django 6.0 on 2025-12-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_value', models.FloatField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed - Valid'), ('FALSE', 'False Alarm'), ('CLOSED', 'Closed')], default='NEW', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('overcrowding_threshold', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventEvidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='image/jpeg', max_length=50)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='surveillance_app.eventlog')),
            ],
        ),
        migrations.AddField(
            model_name='eventlog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveillance_app.eventtype'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Area where the overcrowding occurred.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveillance_app.surveillancearea'),
        ),
    ]
