# Generated by Django 6.0 on 2025-12-13 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the event was reviewed/closed by admin', null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who reviewed or handled this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
