# Generated by Django 5.2.9 on 2026-01-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0002_eventlog_reviewed_at_eventlog_reviewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('lift_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Main Lift', 'Service Lift'", max_length=100, unique=True)),
                ('location', models.CharField(default='Ground Floor', help_text='Building and floor location', max_length=200)),
                ('max_capacity', models.IntegerField(default=8, help_text='Maximum allowed people in lift')),
                ('warning_threshold', models.IntegerField(default=6, help_text='Warning at this count')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lift',
                'verbose_name_plural': 'Lifts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LiftUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times lift used today')),
                ('total_people', models.IntegerField(default=0, help_text='Total people detected today')),
                ('date', models.DateField(auto_now_add=True)),
                ('max_people_count', models.IntegerField(default=0, help_text='Maximum people in single detection today')),
                ('overcrowding_count', models.IntegerField(default=0, help_text='Number of overcrowding incidents today')),
                ('first_usage', models.DateTimeField(auto_now_add=True)),
                ('last_usage', models.DateTimeField(auto_now=True)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='surveillance_app.lift')),
            ],
            options={
                'verbose_name': 'Lift Usage',
                'verbose_name_plural': 'Lift Usages',
                'unique_together': {('lift', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LiftDetection',
            fields=[
                ('detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('people_count', models.IntegerField()),
                ('is_overcrowded', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField()),
                ('image', models.ImageField(upload_to='lift_detections/%Y/%m/%d/')),
                ('processed_image', models.CharField(blank=True, help_text='Path to annotated image', max_length=255)),
                ('detection_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='surveillance_app.lift')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='surveillance_app.liftusage')),
            ],
            options={
                'verbose_name': 'Lift Detection',
                'verbose_name_plural': 'Lift Detections',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who reviewed or handled this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to='surveillance_app.user'),
        ),
    ]
