# Generated by Django 5.2.9 on 2026-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0003_lift_user_liftusage_liftdetection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftdetection',
            name='avg_people_in_video',
            field=models.FloatField(default=0.0, help_text='Average people across sampled frames'),
        ),
        migrations.AddField(
            model_name='liftdetection',
            name='frame_results',
            field=models.JSONField(blank=True, default=list, help_text='Per-frame detection results for video'),
        ),
        migrations.AddField(
            model_name='liftdetection',
            name='max_people_in_video',
            field=models.IntegerField(default=0, help_text='Max people detected in any single frame'),
        ),
        migrations.AddField(
            model_name='liftdetection',
            name='source_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='liftdetection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lift_videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='liftdetection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lift_detections/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='liftdetection',
            name='processed_image',
            field=models.CharField(blank=True, help_text='Path to annotated peak frame image', max_length=255),
        ),
    ]
