# Generated by Django 5.2.9 on 2026-03-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0004_liftdetection_avg_people_in_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftdetection',
            name='processed_video',
            field=models.CharField(blank=True, help_text='Path to annotated video file', max_length=255, null=True),
        ),
    ]
