# Generated by Django 5.2.12 on 2026-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0005_liftdetection_processed_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='max_capacity',
            field=models.IntegerField(default=5, help_text='Maximum allowed people in lift'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='warning_threshold',
            field=models.IntegerField(default=4, help_text='Warning at this count'),
        ),
        migrations.AlterField(
            model_name='liftdetection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lift_detections/'),
        ),
        migrations.AlterField(
            model_name='liftdetection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lift_videos/'),
        ),
    ]
